from tictactoe.Game import Game

game = Game()
moves = game.valid_moves
print(moves)

game.make_move((0))
game.make_move((1))
game.make_move((2))
print(game)
print(moves)
game.make_move((4))
game.make_move((8))
game.make_move((5))
print(game)
print(game)
print(game.winner_exists())
print(moves)
game.make_move(6)
game.make_move(3)
print(game)
print(game.winner_exists())
game.undo_move(3)
print(game)
print(game.winner_exists())
print(game.valid_moves)
game.make_move(3)
print(game)
print(game.winner_exists())
print(game.valid_moves)
# game.make_move(7)
